Fit-Links/FitLink-BE

src/main/java/spring/fitlinkbe/application/auth/AuthFacade.java, src/main/java/spring/fitlinkbe/domain/auth/command/AuthCommand.java, src/main/java/spring/fitlinkbe/domain/member/MemberService.java, src/main/java/spring/fitlinkbe/domain/trainer/AvailableTime.java, src/main/java/spring/fitlinkbe/domain/trainer/Trainer.java, src/main/java/spring/fitlinkbe/domain/trainer/TrainerRepository.java, src/main/java/spring/fitlinkbe/domain/trainer/TrainerService.java, src/main/java/spring/fitlinkbe/infra/trainer/AvailableTimeEntity.java, src/main/java/spring/fitlinkbe/infra/trainer/AvailableTimeJpaRepository.java, src/main/java/spring/fitlinkbe/infra/trainer/TrainerRepositoryImpl.java, src/main/java/spring/fitlinkbe/interfaces/controller/auth/AuthController.java, src/main/java/spring/fitlinkbe/interfaces/controller/auth/dto/AuthDto.java, src/main/java/spring/fitlinkbe/support/utils/RandomStringGenerator.java, src/test/java/spring/fitlinkbe/integration/AuthIntegrationTest.java
- POST `/v1/auth/trainers/register` API 개발
- 테스트 코드 input 검증 위주로 Integration만 작성했고 작업 시간 이슈로 service쪽 검증은 좀 복잡한 비즈니스 로직에서 추가하도록 하겠습니다
- available_time 테이블 추가
=> [FLIZ-84] 트레이너 등록 API 작업

src/main/java/spring/fitlinkbe/application/member/MemberFacade.java, src/main/java/spring/fitlinkbe/domain/common/ConnectingInfoRepository.java, src/main/java/spring/fitlinkbe/domain/common/exception/ErrorCode.java, src/main/java/spring/fitlinkbe/domain/common/model/ConnectingInfo.java, src/main/java/spring/fitlinkbe/domain/member/MemberService.java, src/main/java/spring/fitlinkbe/domain/notification/Notification.java, src/main/java/spring/fitlinkbe/domain/notification/NotificationRepository.java, src/main/java/spring/fitlinkbe/domain/notification/NotificationService.java, src/main/java/spring/fitlinkbe/infra/common/connectingInfo/ConnectingInfoJpaRepository.java, src/main/java/spring/fitlinkbe/infra/common/connectingInfo/ConnectingInfoRepositoryImpl.java, src/main/java/spring/fitlinkbe/infra/notification/NotificationJpaRepository.java, src/main/java/spring/fitlinkbe/infra/notification/NotificationRepositoryImpl.java, src/main/java/spring/fitlinkbe/interfaces/controller/member/MemberController.java, src/test/java/spring/fitlinkbe/integration/MemberIntegrationTest.java, src/test/java/spring/fitlinkbe/integration/common/TestDataHandler.java
- POST `/v1/members/disconnect` api 작업입니다
- 이미 연결 요청중인트레이너 정보가 있으면 연결 요청이 실패하도록 했습니다
=> [FLIZ-93] MEMBER 연결 해제 요청 API 작업

Dockerfile
- GitHub Actions 파이프 라인 구축
- DockerFIle 추가
- GitHub Actions 파이프 라인 구축
-
=> GitHub Actions 파이프 라인 구축

src/main/java/spring/fitlinkbe/application/member/MemberFacade.java, src/main/java/spring/fitlinkbe/application/member/criteria/WorkoutScheduleResult.java, src/main/java/spring/fitlinkbe/domain/member/MemberService.java, src/main/java/spring/fitlinkbe/domain/member/WorkoutScheduleRepository.java, src/main/java/spring/fitlinkbe/infra/member/WorkoutScheduleRepositoryImpl.java, src/main/java/spring/fitlinkbe/interfaces/controller/member/MemberController.java, src/main/java/spring/fitlinkbe/interfaces/controller/member/dto/WorkoutScheduleDto.java, src/test/java/spring/fitlinkbe/integration/MemberIntegrationTest.java, src/test/java/spring/fitlinkbe/integration/common/TestDataHandler.java
- GET `/v1/members/workout-schedule` API 작업했습니다.
- 통합 테스트 추가 (복잡한 비즈니스, 도메인 로직이 생긴다면 유닛 테스트 추가하도록 하겠습니다)
=> [FLIZ-110] 회원 PT 희망시간 조회 API 작업

src/main/java/spring/fitlinkbe/application/member/MemberFacade.java, src/main/java/spring/fitlinkbe/application/member/criteria/WorkoutScheduleCriteria.java, src/main/java/spring/fitlinkbe/domain/common/exception/ErrorCode.java, src/main/java/spring/fitlinkbe/domain/common/model/Token.java, src/main/java/spring/fitlinkbe/domain/member/MemberService.java, src/main/java/spring/fitlinkbe/domain/member/WorkoutSchedule.java, src/main/java/spring/fitlinkbe/domain/member/WorkoutScheduleRepository.java, src/main/java/spring/fitlinkbe/infra/common/token/TokenEntity.java, src/main/java/spring/fitlinkbe/infra/member/WorkoutScheduleJpaRepository.java, src/main/java/spring/fitlinkbe/infra/member/WorkoutScheduleRepositoryImpl.java, src/main/java/spring/fitlinkbe/interfaces/controller/member/MemberController.java, src/main/java/spring/fitlinkbe/interfaces/controller/member/dto/WorkoutScheduleDto.java, src/main/java/spring/fitlinkbe/support/config/ObjectMapperConfig.java, src/main/java/spring/fitlinkbe/support/validator/CollectionValidator.java, src/test/java/spring/fitlinkbe/integration/MemberIntegrationTest.java
- `/v1/members/workout-schedule` PUT api 작업했습니다
- custom validator 추가해서 collection 검증 가능하도록 했습니다
=> [FLIZ-111] PT 희망시간 수정 API 작업

src/main/java/spring/fitlinkbe/application/member/MemberFacade.java, src/main/java/spring/fitlinkbe/application/member/criteria/MemberInfoResult.java, src/main/java/spring/fitlinkbe/domain/common/SessionInfoRepository.java, src/main/java/spring/fitlinkbe/domain/common/model/SessionInfo.java, src/main/java/spring/fitlinkbe/domain/member/MemberRepository.java, src/main/java/spring/fitlinkbe/domain/member/MemberService.java, src/main/java/spring/fitlinkbe/infra/common/sessioninfo/SessionInfoJpaRepository.java, src/main/java/spring/fitlinkbe/infra/common/sessioninfo/SessionInfoRepositoryImpl.java, src/main/java/spring/fitlinkbe/infra/member/MemberJpaRepository.java, src/main/java/spring/fitlinkbe/infra/member/MemberRepositoryCustom.java, src/main/java/spring/fitlinkbe/infra/member/MemberRepositoryCustomImpl.java, src/main/java/spring/fitlinkbe/infra/member/MemberRepositoryImpl.java, src/main/java/spring/fitlinkbe/interfaces/controller/member/MemberController.java, src/main/java/spring/fitlinkbe/interfaces/controller/member/dto/MemberInfoDto.java, src/test/java/spring/fitlinkbe/integration/MemberIntegrationTest.java, src/test/java/spring/fitlinkbe/integration/common/TestDataHandler.java
- GET `/v1/members` api 작업입니다
- request 상태가 아닌 트레이너가 연동 수락한 회원들만 조회하도록 했습니다.
=> [FLIZ-142] 내 회원 리스트 조회 api

src/main/java/spring/fitlinkbe/support/config/ApplicationYmlRead.java, src/main/java/spring/fitlinkbe/support/config/SecurityConfig.java
- cors config 추가
```
app:
cors:
allowed-headers: 
allowed-methods: 
allowed-origins: 
max-age: 
```
,로 구문해서 문자열 각각 넣어주면 됩니다
=> [FLIZ-165] cors config 추가

src/main/java/spring/fitlinkbe/application/trainer/TrainerFacade.java, src/main/java/spring/fitlinkbe/application/trainer/criteria/AvailableTimesResult.java, src/main/java/spring/fitlinkbe/domain/common/exception/ErrorCode.java, src/main/java/spring/fitlinkbe/domain/trainer/AvailableTimeRepository.java, src/main/java/spring/fitlinkbe/domain/trainer/TrainerService.java, src/main/java/spring/fitlinkbe/infra/trainer/AvailableTimeRepositoryImpl.java, src/main/java/spring/fitlinkbe/interfaces/controller/trainer/TrainerController.java, src/main/java/spring/fitlinkbe/interfaces/controller/trainer/dto/AvailableTimesDto.java, src/test/java/spring/fitlinkbe/integration/TrainerIntegrationTest.java
- DELETE `/v1/trainers/me/available-times`
- api 작업했습니다
=> [FLIZ-167] 트레이너 수업 가능 시간 삭제

docker/mysql/initdb.d/create_table.sql, src/main/java/spring/fitlinkbe/infra/reservation/LocalDateTimeListConverter.java, src/main/java/spring/fitlinkbe/infra/reservation/ReservationEntity.java, src/main/java/spring/fitlinkbe/interfaces/controller/auth/dto/AuthDto.java, src/main/resources/application.yml, src/test/resources/application.yml
- JSON -> vachar 타입으로 변경
- core config 추가
=> [Fliz-188] BE hotfix 작업

src/main/java/spring/fitlinkbe/application/trainer/TrainerFacade.java, src/main/java/spring/fitlinkbe/domain/common/exception/ErrorCode.java, src/main/java/spring/fitlinkbe/domain/notification/Notification.java, src/main/java/spring/fitlinkbe/domain/notification/NotificationService.java, src/main/java/spring/fitlinkbe/domain/trainer/TrainerService.java, src/main/java/spring/fitlinkbe/interfaces/controller/trainer/TrainerController.java, src/main/java/spring/fitlinkbe/interfaces/controller/trainer/dto/TrainerDto.java, src/test/java/spring/fitlinkbe/integration/TrainerIntegrationTest.java
- POST `/v1/trainers/disconnect` api 작업했습니다
=> [FLIZ-186] 트레이너 회원 연결 해제 요청 api 작업

docker/mysql/initdb.d/create_table.sql, src/main/java/spring/fitlinkbe/application/reservation/ReservationFacade.java, src/main/java/spring/fitlinkbe/application/reservation/criteria/ReservationCriteria.java, src/main/java/spring/fitlinkbe/domain/common/exception/ErrorCode.java, src/main/java/spring/fitlinkbe/domain/common/model/SessionInfo.java, src/main/java/spring/fitlinkbe/domain/member/MemberService.java, src/main/java/spring/fitlinkbe/domain/notification/Notification.java, src/main/java/spring/fitlinkbe/domain/notification/NotificationStrategyHandler.java, src/main/java/spring/fitlinkbe/domain/notification/command/NotificationCommand.java, src/main/java/spring/fitlinkbe/domain/reservation/Reservation.java, src/main/java/spring/fitlinkbe/domain/reservation/ReservationRepository.java, src/main/java/spring/fitlinkbe/domain/reservation/ReservationService.java, src/main/java/spring/fitlinkbe/domain/reservation/command/ReservationCommand.java, src/main/java/spring/fitlinkbe/infra/reservation/ReservationJpaRepository.java, src/main/java/spring/fitlinkbe/infra/reservation/ReservationRepositoryCustom.java, src/main/java/spring/fitlinkbe/infra/reservation/ReservationRepositoryCustomImpl.java, src/main/java/spring/fitlinkbe/infra/reservation/ReservationRepositoryImpl.java, src/main/java/spring/fitlinkbe/interfaces/controller/reservation/ReservationController.java, src/main/java/spring/fitlinkbe/interfaces/controller/reservation/dto/ReservationRequestDto.java, src/main/java/spring/fitlinkbe/interfaces/controller/reservation/dto/ReservationResponseDto.java, src/main/java/spring/fitlinkbe/interfaces/scheduler/FixedReservationScheduler.java, src/test/java/spring/fitlinkbe/domain/reservation/ReservationServiceTest.java, src/test/java/spring/fitlinkbe/integration/NotificationIntegrationTest.java, src/test/java/spring/fitlinkbe/integration/ReservationIntegrationTest.java, src/test/java/spring/fitlinkbe/interfaces/controller/reservation/ReservationControllerTest.java
- 추가 기능 구현
- 예약 리팩토링 진행
- 예약 관련 리네이밍 진행
- 예약 불가 설정 해지 기능 추가
- 고정 예약 변경 기능 추가
- 고정 예약 프로세스 수정
- 직접 예약 프로세스 수정
- personal_detail 에
- status에 REQUIRED_REGISTER 추가
=> [Fliz-192] BE 예약 로직 보완

src/main/java/spring/fitlinkbe/application/trainer/TrainerFacade.java, src/main/java/spring/fitlinkbe/application/trainer/criteria/AvailableTimesResult.java, src/main/java/spring/fitlinkbe/interfaces/controller/trainer/TrainerController.java, src/main/java/spring/fitlinkbe/interfaces/controller/trainer/dto/AvailableTimesDto.java, src/test/java/spring/fitlinkbe/integration/TrainerIntegrationTest.java
- GET `/v1/trainers/:trainerId/available-times` api 작업했습니다
- 회원이 자신의 트레이너만 수업 가능 시간을 조회할 수 있도록 했습니다
=> [FLIZ-190] 특정 트레이너 수업 가능 시간 조회 api

src/main/java/spring/fitlinkbe/application/member/MemberFacade.java, src/main/java/spring/fitlinkbe/application/member/criteria/MemberInfoResult.java, src/main/java/spring/fitlinkbe/domain/reservation/ReservationRepository.java, src/main/java/spring/fitlinkbe/domain/reservation/ReservationService.java, src/main/java/spring/fitlinkbe/infra/reservation/ReservationJpaRepository.java, src/main/java/spring/fitlinkbe/infra/reservation/ReservationRepositoryImpl.java, src/main/java/spring/fitlinkbe/interfaces/controller/member/dto/MemberInfoDto.java, src/test/java/spring/fitlinkbe/integration/MemberIntegrationTest.java, src/test/java/spring/fitlinkbe/integration/common/TestDataHandler.java
- member 내 정보 조회 api 에 고정 예약 정보 추가
- trainer 회원 정보 조회 api 에 고정 예약 정보 추가
=> [FLIZ-208] 고정 예약 정보 회원 정보 조회시 같이 조회되도록 추가

.github/workflows/deploy-dev.yml, Dockerfile, src/main/java/spring/fitlinkbe/FitLinkBeApplication.java, src/test/java/spring/fitlinkbe/integration/ReservationIntegrationTest.java, src/test/resources/application.yml
- dev 서버 배포 git action 추가했습니다
- pr 시에는 Test만, dev 머지 후에는 deploy까지 진행되도록 했습니다
- Reservation test 하나 주석 처리 했는데 시간 관련 로직이 Git actions 환경이랑 좀 달라서 테스트 실패하는 것 같습니다 이건 추후에 수정해야 할 것 같습니다
=> git actions 배포 자동화 작업

src/main/java/spring/fitlinkbe/application/trainer/TrainerFacade.java, src/main/java/spring/fitlinkbe/domain/common/ConnectingInfoRepository.java, src/main/java/spring/fitlinkbe/domain/common/model/ConnectingInfo.java, src/main/java/spring/fitlinkbe/domain/notification/Notification.java, src/main/java/spring/fitlinkbe/domain/notification/NotificationRepository.java, src/main/java/spring/fitlinkbe/domain/notification/NotificationService.java, src/main/java/spring/fitlinkbe/domain/notification/NotificationStrategyHandler.java, src/main/java/spring/fitlinkbe/domain/notification/command/NotificationCommand.java, src/main/java/spring/fitlinkbe/domain/trainer/TrainerService.java, src/main/java/spring/fitlinkbe/infra/common/connectingInfo/ConnectingInfoRepositoryImpl.java, src/main/java/spring/fitlinkbe/infra/notification/NotificationRepositoryImpl.java, src/main/java/spring/fitlinkbe/interfaces/controller/trainer/TrainerController.java, src/main/java/spring/fitlinkbe/interfaces/controller/trainer/dto/ConnectRequestDecisionDto.java, src/test/java/spring/fitlinkbe/integration/TrainerIntegrationTest.java, src/test/java/spring/fitlinkbe/integration/common/TestDataHandler.java
- POST `/v1/trainers/connect-requests/{notificationId}/decision` api 작업했습니다
- notification 전송하는쪽 로직 추가했는데 이쪽 제대로 되어있나 뵈주시면 감사하겠습니다
=> [FLIZ-243] trainer 연동 요청 처리 api 작업

src/main/java/spring/fitlinkbe/application/attachment/AttachmentFacade.java, src/main/java/spring/fitlinkbe/application/auth/AuthFacade.java, src/main/java/spring/fitlinkbe/application/member/criteria/MemberInfoResult.java, src/main/java/spring/fitlinkbe/application/trainer/TrainerFacade.java, src/main/java/spring/fitlinkbe/domain/attachment/AttachmentService.java, src/main/java/spring/fitlinkbe/domain/common/SessionInfoRepository.java, src/main/java/spring/fitlinkbe/domain/notification/Notification.java, src/main/java/spring/fitlinkbe/domain/notification/NotificationService.java, src/main/java/spring/fitlinkbe/domain/trainer/Trainer.java, src/main/java/spring/fitlinkbe/domain/trainer/TrainerService.java, src/main/java/spring/fitlinkbe/infra/common/sessioninfo/SessionInfoJpaRepository.java, src/main/java/spring/fitlinkbe/infra/common/sessioninfo/SessionInfoRepositoryImpl.java, src/main/java/spring/fitlinkbe/infra/trainer/TrainerEntity.java, src/main/java/spring/fitlinkbe/interfaces/controller/member/dto/MemberInfoDto.java, src/test/java/spring/fitlinkbe/integration/AttachmentIntegrationTest.java, src/test/java/spring/fitlinkbe/integration/AuthIntegrationTest.java, src/test/java/spring/fitlinkbe/integration/MemberIntegrationTest.java, src/test/java/spring/fitlinkbe/integration/TrainerIntegrationTest.java, src/test/java/spring/fitlinkbe/integration/common/TestDataHandler.java
- 내정보 조회시 Trainer 정보 추가
- 트레이너 연동 수락시 session info 생성하도록 수정
- trainer Table 에 phone, profile url 추가
=> [FLIZ-244] 내정보 조회, 트레이너 연동 api 수정 작업

docker/mysql/initdb.d/create_table.sql, src/main/java/spring/fitlinkbe/domain/trainer/Trainer.java
- DB 스키마 최신화
- DDL 최신화
- 설계와 다른 enum 값들 최신화 하였습니다.
=> [Fliz-258] BE db 스키마 최신화

docker/mysql/initdb.d/create_table.sql, src/main/java/spring/fitlinkbe/domain/auth/command/AuthCommand.java, src/main/java/spring/fitlinkbe/infra/trainer/AvailableTimeEntity.java
- 트레이너 등록시 pt 가능 시간에 적용일자 추가했습니다
- availableTime applyAt 컬럼에 Not null 제약조건 추가했습니다
=> [FLIZ-259] 트레이너 등록 api 수정 작업

src/main/java/spring/fitlinkbe/application/member/criteria/MemberInfoResult.java, src/main/java/spring/fitlinkbe/application/notification/NotificationFacade.java, src/main/java/spring/fitlinkbe/application/notification/criteria/NotificationCriteria.java, src/main/java/spring/fitlinkbe/application/trainer/TrainerFacade.java, src/main/java/spring/fitlinkbe/domain/notification/NotificationRepository.java, src/main/java/spring/fitlinkbe/domain/notification/NotificationService.java, src/main/java/spring/fitlinkbe/domain/notification/command/NotificationCommand.java, src/main/java/spring/fitlinkbe/infra/notification/NotificationRepositoryCustom.java, src/main/java/spring/fitlinkbe/infra/notification/NotificationRepositoryCustomImpl.java, src/main/java/spring/fitlinkbe/infra/notification/NotificationRepositoryImpl.java, src/main/java/spring/fitlinkbe/infra/trainer/TrainerEntity.java, src/main/java/spring/fitlinkbe/interfaces/controller/notification/NotificationController.java, src/test/java/spring/fitlinkbe/domain/notification/NotificationServiceTest.java, src/test/java/spring/fitlinkbe/integration/NotificationIntegrationTest.java, src/test/java/spring/fitlinkbe/interfaces/controller/notification/NotificationControllerTest.java
- 알림 정보 조회 로직 수정
- 알림 정보 조회할 때 특정 회원에 대한 정보 조회할 수 있게 옵션 추가
- 없습니다.
=> [Fliz-271] BE 알림 정보 조회 리팩토링

src/main/java/spring/fitlinkbe/application/auth/AuthFacade.java, src/main/java/spring/fitlinkbe/domain/common/exception/ErrorCode.java, src/main/java/spring/fitlinkbe/domain/common/model/Token.java, src/main/java/spring/fitlinkbe/interfaces/controller/auth/AuthController.java, src/main/java/spring/fitlinkbe/interfaces/controller/auth/dto/AuthDto.java, src/main/java/spring/fitlinkbe/interfaces/controller/common/exception/ApiControllerAdvice.java, src/main/java/spring/fitlinkbe/support/config/SecurityConfig.java, src/main/java/spring/fitlinkbe/support/security/AuthTokenProvider.java, src/test/java/spring/fitlinkbe/integration/AuthIntegrationTest.java, src/test/java/spring/fitlinkbe/integration/common/TestDataHandler.java
- access token 재발급 api 작업했습니다
- 지금 보니까 access token 1일, refresh token 30일로 유효기간 세팅 해놨었네요
=> [FLIZ-267] 토큰 재발급 api 작업
